"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
sys.setrecursionlimit(4000)


APP = ['main.py']
DATA_FILES = [('scripts', ['scripts/hill-averages.py', 'scripts/mm-best_fit.py'])]
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'kat.icns',
    'packages': ['PySide6', 'scipy', 'pandas', 'matplotlib', 'sympy']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
